- name: My first play
  hosts: myhosts
  # requires set up of ssh key gen
  remote_user: root
  # This will not work without python already install on the server. See readme.md for more details.
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
    
    - name: Check Running Containers
      command: docker ps 
      register: docker_ps_output

    - name: Output running containers
      debug:
        var: docker_ps_output.stdout_lines

    - name: Fetch Running Container Ids
      command: docker ps -q
      register: docker_ids_output

    - name: Output running container Ids
      debug:
        var: docker_ids_output.stdout_lines

    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: compose_installed
      ignore_errors: true

    # parse current tag version from the curl response and then attempt the install
    - name: Get latest Docker Compose version
      uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        return_content: yes
      register: compose_info

    - name: Parse latest version from JSON
      set_fact:
        latest_compose_version: "{{ compose_info.json.tag_name }}"

    - name: Download Docker Compose binary
      get_url: 
        url: "https://github.com/docker/compose/releases/download/{{ latest_compose_version }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'  # Set executable permissions directly

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: compose_version_output

    - name: Display Docker Compose version
      debug:
        var: compose_version_output.stdout

    #- name: Pull Jenkins Image
    #  command: docker pull 
